#!/bin/bash

set -eu

git clone ${REPO_ROOT:?required} ${REPO_OUT:?required}

pushd cfcr-manifests
tar xfz source.tar.gz
popd
raw_cfcr_manifests=$(ls -d cfcr-manifests/cloudfoundry-incubator-kubo-deployment*/manifests)

STEMCELL_OS=${STEMCELL_OS:-ubuntu-trusty}
STEMCELL_VERSION=$(cat stemcell/version)

releases=($(ls -d *-compiled-release))

rm -f ${REPO_OUT}/use-compiled-releases.yml
for release in "${releases[@]}"; do

  tar -xzf $release/*.tgz $( tar -tzf $release/*.tgz | grep 'release.MF' )
  release_name=$( grep -E '^name: ' release.MF | awk '{print $2}' | tr -d "\"'" )
  release_version=$( grep -E '^version: ' release.MF | awk '{print $2}' | tr -d "\"'" )
  release_url=$(cat $release/url)
  release_sha1=$(sha1sum $release/*.tgz | awk '{print $1}')

  cat >> ${REPO_OUT}/use-compiled-releases.yml <<-YAML
- path: /releases/name=${release_name}
  type: replace
  value:
    name:    "${release_name}"
    url:     "${release_url}"
    version: "${release_version}"
    sha1:    "${release_sha1}"
    stemcell:
      os: "${STEMCELL_OS}"
      version: "${STEMCELL_VERSION}"

YAML
done

rm -rf cfcr
mkdir -p cfcr
cp -r $raw_cfcr_manifests/ops-files ${REPO_OUT}/cfcr/
cp -r $raw_cfcr_manifests/helper    ${REPO_OUT}/cfcr/

spruce merge --go-patch \
  $raw_cfcr_manifests/cfcr.yml \
  ${REPO_OUT}/use-compiled-releases.yml > ${REPO_OUT}/cfcr.yml

if [[ -z $(git config --global user.email) ]]; then
  git config --global user.email "${GIT_EMAIL}"
fi
if [[ -z $(git config --global user.name) ]]; then
  git config --global user.name "${GIT_NAME}"
fi

pushd $REPO_OUT
  git merge --no-edit ${REPO_OUT_BRANCH}
  git add -A
  git status
  git commit -m "Bumped cfcr.yml"
popd
